Lesson21
marcelomatosdev/comit-exercises pull request #5
Opened 2020-09-25 23:22 UTC by marcelomatosdev

2020-09-26 20:53 UTC, anton-shevchook commented on Lesson21/index.js
> +let secondNumber = prompt('Please enter the second number', 0);
It's better to convert prompt entered values into "number" type before converting.

2020-09-26 20:56 UTC, anton-shevchook requested changes
- [ ] [Convert to "number" type.](https://github.com/marcelomatosdev/comit-exercises/pull/5/files#r495494497)
Good that you used backtick template syntax,
you'll be using it often!
Please fix types, test it out and you can merge it.

2020-09-28 15:42 UTC, marcelomatosdev reviewed
Converted to Number

2020-09-30 21:06 UTC, anton-shevchook approved these changes
Good job!
You can merge it.

2020-10-01 01:28 UTC, merged